# Generated by Django 5.0.5 on 2024-06-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_shop_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='datetime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_people',
            new_name='num_people',
        ),
    ]
