# Generated by Django 5.0.5 on 2024-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='評価'),
        ),
        migrations.AddField(
            model_name='shop',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地域'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price_range',
            field=models.IntegerField(blank=True, null=True, verbose_name='予算'),
        ),
    ]
