# Generated by Django 5.0.5 on 2024-10-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_shop_rating_shop_region_alter_shop_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, choices=[('北区', '北区'), ('南区', '南区'), ('東区', '東区'), ('西区', '西区')], max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price_range',
            field=models.IntegerField(blank=True, choices=[(1000, '1000円'), (2000, '2000円'), (3000, '3000円'), (5000, '5000円')], null=True, verbose_name='予算'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.IntegerField(choices=[(1, '1.0'), (2, '2.0'), (3, '3.0'), (4, '4.0'), (5, '5.0')], default=3, verbose_name='評価'),
        ),
    ]
