# Generated by Django 5.0.5 on 2024-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_shop_address_alter_shop_price_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3, verbose_name='評価'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='region',
            field=models.CharField(blank=True, choices=[('北区', '北区'), ('南区', '南区'), ('東区', '東区'), ('西区', '西区')], max_length=10, null=True, verbose_name='地域'),
        ),
    ]
