# Generated by Django 5.0.5 on 2024-10-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_shop_address_alter_shop_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price_range',
            field=models.CharField(blank=True, choices=[(1000, '1000円'), (2000, '2000円'), (3000, '3000円'), (5000, '5000円')], max_length=10, null=True, verbose_name='予算'),
        ),
    ]
