# Generated by Django 5.0.5 on 2024-10-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_shop_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='region',
            field=models.CharField(blank=True, choices=[('北区', '北区'), ('昭和区', '昭和区'), ('中区', '中区'), ('瑞穂区', '瑞穂区')], max_length=10, null=True, verbose_name='地域'),
        ),
    ]
