# Generated by Django 5.0.5 on 2024-10-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_shop_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='rating',
        ),
        migrations.AlterField(
            model_name='shop',
            name='price_range',
            field=models.CharField(blank=True, choices=[('1000', '1000円'), ('2000', '2000円'), ('3000', '3000円'), ('5000', '5000円')], max_length=10, null=True, verbose_name='予算'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='region',
            field=models.CharField(blank=True, choices=[('北区', '北区'), ('昭和区', '昭和区'), ('中区', '中区')], max_length=10, null=True, verbose_name='地域'),
        ),
    ]
